apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- 02was.yaml
resources:
- 02was.yaml
images:
- name: cicd-image
  newName: public.ecr.aws/o7v7w4z5/was
  newTag: v28
